apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    app: frontend

spec:
  containers:
    - name: frontend
      image: nginx:latest
      ports:
        - containerPort: 80

  configMapRef:
    name: DB-config