apiVersion: v1
kind: pod
metadata:
  name: env-demo
spec:
  containers:
    - name: env-demo
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: DB_HOST
          value: "MYSQL-SERVI`CE"
        - name: DB_PORT
          value: "3306"