apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: roboshop
type: NodePort

spec:
  selector:
    project: roboshop
    app: multicontainer

  ports:
  - protocol: TCP
    port: 80  #service port
    targetPort: 80 #container port
    nodePort: 30080  #node port