apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  
  labels:
    app: nginx  

    # the namespace in which the deployment will be created 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

# the pod template

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
